'use client';

import type { Machine, MachineEvent, Tool, PowerMetrics } from '@/types';

// Mock Machines Data
export const mockMachines: Machine[] = [
  {
    id: 'M001',
    code: 'KUKA-01',
    name: 'Robot Hàn KUKA Cell',
    type: 'robot-welding',
    category: 'robot_only',
    brand: 'KUKA',
    controller: 'KUKA KR C4',
    plc: 'Siemens S7-1200',
    status: 'RUN',
    mode: 'AUTO',
    image: '/img/kukarobot.jpeg',
    oee: 87,
    availability: 92,
    performance: 95,
    quality: 96,
    powerKw: 24.5,
    energyTodayKwh: 187.2,
    energyMonthKwh: 4123.8,
    cycleTimeSec: 45,
    idealCycleTimeSec: 42,
    partCount: 1024,
    goodCount: 985,
    ngCount: 39,
    machineHealth: 85,
    maintenanceDueDays: 12,
    anomalyScore: 0.15,
    activeAlarms: 1,
    toolLifeRemainingPct: 65,
    weldingCurrentA: 185,
    servoLoadPct: 72,
    temperatureC: 45,
    currentProgram: 'WELD_PART_A123',
    area: 'Assembly Line A',
    rawTelemetry: {
      state: 'RUN',
      mode: 'AUTO',
      powerKw: 24.5,
      temperatureC: 45,
      servoLoadPct: 72,
      programName: 'WELD_PART_A123',
    },
    computedMetrics: {
      oee: 87,
      availability: 92,
      performance: 95,
      quality: 96,
      healthScore: 85,
      mtbf: 128,
      mttr: 2.8,
    },
    predictions: {
      remainingToolLifePct: 65,
      remainingMaintenanceHours: 96,
      maintenanceRisk: 'medium',
      predictedFailureWindow: '10-14 days',
      recommendation: 'Inspect weld gun tip and clean torch cable routing',
    },
  },
  {
    id: 'M002',
    code: 'CNC-MILL-01',
    name: 'Máy Phay CNC Sinumerik',
    type: 'cnc-milling',
    category: 'cnc_machine',
    brand: 'Siemens Sinumerik',
    controller: 'Siemens 840D SL',
    plc: 'Siemens S7-1500',
    status: 'RUN',
    mode: 'AUTO',
    image: '/img/may.png',
    oee: 82,
    availability: 88,
    performance: 93,
    quality: 92,
    powerKw: 18.7,
    energyTodayKwh: 145.6,
    energyMonthKwh: 3267.4,
    cycleTimeSec: 120,
    idealCycleTimeSec: 115,
    partCount: 512,
    goodCount: 498,
    ngCount: 14,
    machineHealth: 78,
    maintenanceDueDays: 7,
    anomalyScore: 0.28,
    activeAlarms: 2,
    toolLifeRemainingPct: 38,
    spindleSpeedRpm: 3850,
    feedRateMmMin: 450,
    cuttingSpeedMMin: 120,
    depthOfCutMm: 2.5,
    feedPerToothMm: 0.05,
    widthOfCutMm: 8.0,
    materialRemovalRateCm3Min: 45.3,
    spindleLoadPct: 68,
    vibrationPct: 42,
    temperatureC: 62,
    currentProgram: 'MILL_PART_B456',
    area: 'Machining Center',
    rawTelemetry: {
      state: 'RUN',
      mode: 'AUTO',
      powerKw: 18.7,
      temperatureC: 62,
      vibrationPct: 42,
      spindleRpm: 3850,
      feedRateMmMin: 450,
      programName: 'MILL_PART_B456',
    },
    computedMetrics: {
      oee: 82,
      availability: 88,
      performance: 93,
      quality: 92,
      healthScore: 78,
      mtbf: 96,
      mttr: 4.1,
    },
    predictions: {
      remainingToolLifePct: 38,
      remainingMaintenanceHours: 54,
      maintenanceRisk: 'high',
      predictedFailureWindow: '5-8 days',
      recommendation: 'Replace tool T45 and inspect spindle bearing vibration',
    },
  },
  {
    id: 'M003',
    code: 'CNC-TURN-01',
    name: 'Máy Tiện CNC',
    type: 'cnc-turning',
    category: 'cnc_machine',
    brand: 'Haas',
    controller: 'Haas CNC',
    plc: 'Siemens S7-1200',
    status: 'IDLE',
    mode: 'AUTO',
    image: '/img/maycat.png',
    oee: 0,
    availability: 100,
    performance: 0,
    quality: 0,
    powerKw: 2.1,
    energyTodayKwh: 12.3,
    energyMonthKwh: 892.5,
    cycleTimeSec: 85,
    idealCycleTimeSec: 80,
    partCount: 0,
    goodCount: 0,
    ngCount: 0,
    machineHealth: 82,
    maintenanceDueDays: 21,
    anomalyScore: 0.05,
    activeAlarms: 0,
    toolLifeRemainingPct: 72,
    spindleSpeedRpm: 0,
    feedRateMmMin: 0,
    cuttingSpeedMMin: 0,
    depthOfCutMm: 0,
    feedPerToothMm: 0,
    widthOfCutMm: 0,
    materialRemovalRateCm3Min: 0,
    spindleLoadPct: 0,
    vibrationPct: 5,
    temperatureC: 35,
    currentProgram: 'IDLE',
    area: 'Machining Center',
    rawTelemetry: {
      state: 'IDLE',
      mode: 'AUTO',
      powerKw: 2.1,
      temperatureC: 35,
      vibrationPct: 5,
      spindleRpm: 0,
      feedRateMmMin: 0,
      programName: 'IDLE',
    },
    computedMetrics: {
      oee: 0,
      availability: 100,
      performance: 0,
      quality: 0,
      healthScore: 82,
      mtbf: 142,
      mttr: 1.9,
    },
    predictions: {
      remainingToolLifePct: 72,
      remainingMaintenanceHours: 220,
      maintenanceRisk: 'low',
      predictedFailureWindow: 'Not in next 30 days',
      recommendation: 'Continue normal operation monitoring',
    },
  },
  {
    id: 'M004',
    code: 'ROBOT-PP-01',
    name: 'Robot Gắp/Đặt Leantec',
    type: 'pick-place',
    category: 'robot_only',
    brand: 'Leantec',
    controller: 'Leantec Control',
    plc: 'Delta DVP',
    status: 'RUN',
    mode: 'AUTO',
    image: '/img/leantec-robot.jpeg',
    oee: 89,
    availability: 94,
    performance: 96,
    quality: 97,
    powerKw: 12.3,
    energyTodayKwh: 98.4,
    energyMonthKwh: 2134.6,
    cycleTimeSec: 35,
    idealCycleTimeSec: 34,
    partCount: 1456,
    goodCount: 1412,
    ngCount: 44,
    machineHealth: 88,
    maintenanceDueDays: 18,
    anomalyScore: 0.12,
    activeAlarms: 0,
    toolLifeRemainingPct: 58,
    servoLoadPct: 55,
    temperatureC: 40,
    currentProgram: 'PP_PART_C789',
    area: 'Assembly Line B',
    rawTelemetry: {
      state: 'RUN',
      mode: 'AUTO',
      powerKw: 12.3,
      temperatureC: 40,
      servoLoadPct: 55,
      programName: 'PP_PART_C789',
    },
    computedMetrics: {
      oee: 89,
      availability: 94,
      performance: 96,
      quality: 97,
      healthScore: 88,
      mtbf: 156,
      mttr: 1.5,
    },
    predictions: {
      remainingToolLifePct: 58,
      remainingMaintenanceHours: 130,
      maintenanceRisk: 'medium',
      predictedFailureWindow: '14-20 days',
      recommendation: 'Check end-effector vacuum seal and gripper pads',
    },
  },
  {
    id: 'M005',
    code: 'CELL-POLISH-01',
    name: 'Cell Cắt & Máy Laser',
    type: 'cutting-polishing',
    category: 'robot_cnc_cell',
    brand: 'Custom Automation',
    controller: 'PLC Mitsubishi',
    plc: 'Mitsubishi FX5',
    status: 'FAULT',
    mode: 'AUTO',
    image: '/img/Cong-Nghe-Laser-50.png',
    oee: 0,
    availability: 0,
    performance: 0,
    quality: 0,
    powerKw: 0,
    energyTodayKwh: 0,
    energyMonthKwh: 1523.2,
    cycleTimeSec: 95,
    idealCycleTimeSec: 90,
    partCount: 234,
    goodCount: 215,
    ngCount: 19,
    machineHealth: 42,
    maintenanceDueDays: 2,
    anomalyScore: 0.82,
    activeAlarms: 3,
    toolLifeRemainingPct: 8,
    spindleLoadPct: 0,
    vibrationPct: 88,
    temperatureC: 78,
    currentProgram: 'FAULT_MODE',
    area: 'Finishing Department',
    rawTelemetry: {
      state: 'FAULT',
      mode: 'AUTO',
      powerKw: 0,
      temperatureC: 78,
      vibrationPct: 88,
      spindleRpm: 0,
      programName: 'FAULT_MODE',
    },
    computedMetrics: {
      oee: 0,
      availability: 0,
      performance: 0,
      quality: 0,
      healthScore: 42,
      mtbf: 48,
      mttr: 7.2,
    },
    predictions: {
      remainingToolLifePct: 8,
      remainingMaintenanceHours: 6,
      maintenanceRisk: 'high',
      predictedFailureWindow: 'Within 24 hours',
      recommendation: 'Immediate inspection: cooling circuit and vibration source',
    },
  },
];

// Mock Events Data
export const generateMockEvents = (): MachineEvent[] => {
  const causes = [
    'Tool wear detected',
    'High vibration',
    'Temperature exceeds limit',
    'Cycle time delay',
    'Operator intervention',
    'Power fluctuation',
    'Scheduled maintenance',
    'Sensor malfunction',
  ];

  const causes_vi = [
    'Phát hiện mòn dao',
    'Độ rung cao',
    'Vượt ngưỡng nhiệt độ',
    'Trễ chu kỳ',
    'Can thiệp của vận hành viên',
    'Dao động nguồn điện',
    'Bảo trì định kỳ',
    'Cảm biến lỗi',
  ];

  const events: MachineEvent[] = [
    {
      id: 'E001',
      machineId: 'M001',
      timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
      type: 'warning',
      severity: 'warning',
      title: 'High Servo Load',
      title_vi: 'Tải Servo Cao',
      message: 'Servo load exceeded 75% threshold',
      message_vi: 'Tải servo vượt ngưỡng 75%',
      durationMin: 0,
      startTime: new Date(Date.now() - 5 * 60000).toISOString(),
      cause: causes[0],
      cause_vi: causes_vi[0],
      acknowledged: false,
      plannedType: 'unplanned',
      stopReasonCode: 'TOOL_WEAR',
    },
    {
      id: 'E002',
      machineId: 'M002',
      timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
      type: 'warning',
      severity: 'warning',
      title: 'Tool Life Low',
      title_vi: 'Tuổi Thọ Dao Thấp',
      message: 'Tool T45 approaching end of life (38% remaining)',
      message_vi: 'Dao T45 sắp hết tuổi thọ (còn 38%)',
      durationMin: 0,
      startTime: new Date(Date.now() - 15 * 60000).toISOString(),
      cause: causes[0],
      cause_vi: causes_vi[0],
      acknowledged: false,
      plannedType: 'unplanned',
      stopReasonCode: 'TOOL_WEAR',
    },
    {
      id: 'E003',
      machineId: 'M002',
      timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
      type: 'downtime',
      severity: 'critical',
      title: 'Unplanned Downtime',
      title_vi: 'Dừng Máy Đột Xuất',
      message: 'Machine stopped unexpectedly',
      message_vi: 'Máy dừng đột ngột',
      durationMin: 8,
      startTime: new Date(Date.now() - 53 * 60000).toISOString(),
      endTime: new Date(Date.now() - 45 * 60000).toISOString(),
      cause: causes[5],
      cause_vi: causes_vi[5],
      acknowledged: true,
      acknowledgedBy: 'Supervisor A',
      plannedType: 'unplanned',
      stopReasonCode: 'POWER_FLUCT',
    },
    {
      id: 'E004',
      machineId: 'M005',
      timestamp: new Date(Date.now() - 2 * 60000).toISOString(),
      type: 'critical',
      severity: 'critical',
      title: 'Machine Fault',
      title_vi: 'Lỗi Máy',
      message: 'Critical fault detected - Immediate maintenance required',
      message_vi: 'Phát hiện lỗi nghiêm trọng - Cần bảo trì ngay',
      durationMin: 0,
      startTime: new Date(Date.now() - 2 * 60000).toISOString(),
      cause: causes[7],
      cause_vi: causes_vi[7],
      acknowledged: false,
      plannedType: 'unplanned',
      stopReasonCode: 'SENSOR_FAULT',
    },
    {
      id: 'E005',
      machineId: 'M005',
      timestamp: new Date(Date.now() - 25 * 60000).toISOString(),
      type: 'warning',
      severity: 'warning',
      title: 'Abnormal Vibration',
      title_vi: 'Độ Rung Bất Thường',
      message: 'Vibration level increased by 35%',
      message_vi: 'Độ rung tăng 35%',
      durationMin: 18,
      startTime: new Date(Date.now() - 43 * 60000).toISOString(),
      endTime: new Date(Date.now() - 25 * 60000).toISOString(),
      cause: causes[1],
      cause_vi: causes_vi[1],
      acknowledged: true,
      acknowledgedBy: 'Technician B',
      plannedType: 'unplanned',
      stopReasonCode: 'HIGH_VIB',
    },
    {
      id: 'E006',
      machineId: 'M001',
      timestamp: new Date(Date.now() - 120 * 60000).toISOString(),
      type: 'info',
      severity: 'info',
      title: 'Maintenance Completed',
      title_vi: 'Hoàn Thành Bảo Trì',
      message: 'Scheduled maintenance completed successfully',
      message_vi: 'Bảo trì định kỳ đã hoàn thành thành công',
      durationMin: 65,
      startTime: new Date(Date.now() - 185 * 60000).toISOString(),
      endTime: new Date(Date.now() - 120 * 60000).toISOString(),
      cause: 'Routine maintenance',
      cause_vi: 'Bảo trì định kỳ',
      acknowledged: true,
      acknowledgedBy: 'Planner',
      plannedType: 'planned',
      stopReasonCode: 'SCHEDULED_MNT',
    },
  ];

  return events;
};

// Mock Tools Data
export const mockTools: Tool[] = [
  {
    id: 'T001',
    machineId: 'M002',
    name: 'End Mill T45 Ø10mm',
    type: 'End Mill',
    remainingLifePct: 38,
    estimatedPartsRemaining: 156,
    estimatedHoursRemaining: 12.5,
    usageTimeHours: 68.3,
    wearTrend: [0, 8, 16, 25, 32, 38],
    lastReplacedDate: '2026-03-01',
  },
  {
    id: 'T002',
    machineId: 'M002',
    name: 'Slot Drill T52 Ø8mm',
    type: 'Slot Drill',
    remainingLifePct: 72,
    estimatedPartsRemaining: 412,
    estimatedHoursRemaining: 35.2,
    usageTimeHours: 28.9,
    wearTrend: [0, 6, 12, 19, 28],
    lastReplacedDate: '2026-02-15',
  },
  {
    id: 'T003',
    machineId: 'M005',
    name: 'Diamond Bit Cutting D15',
    type: 'Cutting Bit',
    remainingLifePct: 8,
    estimatedPartsRemaining: 12,
    estimatedHoursRemaining: 1.2,
    usageTimeHours: 125.8,
    wearTrend: [0, 15, 28, 45, 62, 78, 88],
    lastReplacedDate: '2026-01-20',
  },
  {
    id: 'T004',
    machineId: 'M001',
    name: 'Welding Gun Tip Cu',
    type: 'Electrode',
    remainingLifePct: 65,
    estimatedPartsRemaining: 8500,
    estimatedHoursRemaining: 145.3,
    usageTimeHours: 78.2,
    wearTrend: [0, 5, 12, 18, 28, 35],
    lastReplacedDate: '2026-02-28',
  },
];

// Power metrics history
export const generatePowerMetricsHistory = (): PowerMetrics[] => {
  const metrics: PowerMetrics[] = [];
  const now = Date.now();

  for (let i = 23; i >= 0; i--) {
    const timestamp = new Date(now - i * 3600000);
    metrics.push({
      timestamp: timestamp.toISOString(),
      voltageV: 400 + Math.random() * 10 - 5,
      currentA: 50 + Math.random() * 30,
      powerKw: 55 + Math.random() * 25 - Math.sin(i / 4) * 10,
      energyKwh: (i + 1) * 7.8 + Math.random() * 2,
      frequency: 50 + Math.random() * 0.2 - 0.1,
      powerFactor: 0.92 + Math.random() * 0.05,
      thd: 4 + Math.random() * 2,
    });
  }

  return metrics;
};

// Machine parameters historical data
export const generateMachineTimeSeries = (machineId: string) => {
  const data: any[] = [];
  const now = Date.now();
  const machine = mockMachines.find((m) => m.id === machineId);

  if (!machine) return data;

  for (let i = 119; i >= 0; i--) {
    const timestamp = new Date(now - i * 300000); // 5-minute intervals
    data.push({
      timestamp: timestamp.toISOString(),
      power: machine.powerKw + (Math.random() - 0.5) * 4,
      cycleTime: machine.cycleTimeSec + (Math.random() - 0.5) * 10,
      spindleLoad: machine.spindleLoadPct ? machine.spindleLoadPct + (Math.random() - 0.5) * 15 : null,
      temperature: (machine.temperatureC || 40) + (Math.random() - 0.5) * 8,
      vibration: (machine.vibrationPct || 20) + Math.random() * 10,
      oee: machine.oee + (Math.random() - 0.5) * 5,
    });
  }

  return data;
};

// Downtime events for Pareto chart
export const generateDowntimeEvents = () => {
  return [
    { cause: 'Tool Wear', duration: 156, count: 8 },
    { cause: 'Power Fluctuation', duration: 98, count: 5 },
    { cause: 'Sensor Malfunction', duration: 72, count: 4 },
    { cause: 'Maintenance', duration: 240, count: 3 },
    { cause: 'Operator Intervention', duration: 45, count: 6 },
    { cause: 'Mechanical Issue', duration: 128, count: 2 },
  ];
};

// Pareto OEE root causes
export const generateOEERootCauses = () => {
  return [
    { cause: 'Equipment Downtime', impact: 28 },
    { cause: 'Reduced Speed', impact: 22 },
    { cause: 'Quality Defects', impact: 18 },
    { cause: 'Setup Loss', impact: 15 },
    { cause: 'Adjustment', impact: 12 },
    { cause: 'Other', impact: 5 },
  ];
};

